name: Deploy to Vercel (prod)

on:
  push:
    branches:
      - prod
  workflow_dispatch:

concurrency:
  group: vercel-prod-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    env:
      VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
      VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
      VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Pull Vercel environment (production)
        run: npx vercel pull --yes --environment=production --token=$VERCEL_TOKEN

      - name: Build (production)
        run: npx vercel build --prod --token=$VERCEL_TOKEN

      - name: Deploy (production)
        run: npx vercel deploy --prebuilt --prod --token=$VERCEL_TOKEN


